version: "3"

volumes:
  mysql:
    driver: local
  wordpress:
    driver: local

services:
  mysqlwp:
    restart: always
    image: mariadb:focal
    container_name: mysqlwp
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    security_opt:
      - no-new-privileges
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=wordpress
    volumes:
      - /media/wordpress/mysql:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  blog:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    security_opt:
      - no-new-privileges
    networks:
      - internal
      - nextcloud
    depends_on:
      - mysqlwp
    labels:
      # wordpress
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${HOST_DOMAIN}`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.wordpress.middlewares=securedwp"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.http.middlewares.wordpress.headers.sslredirect=true"
      - "traefik.http.middlewares.securedwp.chain.middlewares=wordpress,lista-blanca-wordpress"
      - "traefik.http.middlewares.lista-blanca-wordpress.ipwhitelist.sourcerange=127.0.0.1/32, 192.168.1.0/24"
    environment:
      WORDPRESS_DB_PASSWORD: ${PASSWORD}
      WORDPRESS_DB_HOST: mysqlwp:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
    volumes:
      - /media/wordpress/wordpress:/var/www/html

networks:
  nextcloud:
    external: true
  internal:
    external: false
