version: "3"

volumes:
  mysql:
    driver: local
  wordpress:
    driver: local

services:
  mysql_wordpress:
    restart: always
    image: mariadb
    container_name: mariadb_wordpress
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD='your_passwd'
      - MYSQL_PASSWORD='your_passwd'
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
    volumes:
      - /home/jrodenas/docker/wordpress/mysql:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  blog:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    networks:
      - internal
      - nextcloud
    depends_on:
      - mysql_wordpress
    labels:
      # wordpress
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`blog.nasaus.es`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.wordpress.middlewares=securedwp"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.http.middlewares.wordpress.headers.sslredirect=true"
      - "traefik.http.middlewares.securedwp.chain.middlewares=wordpress,lista-blanca-wordpress"
      - "traefik.http.middlewares.lista-blanca-wordpress.ipwhitelist.sourcerange='your_ips"
    environment:
      WORDPRESS_DB_PASSWORD: 'your_passwd'
      WORDPRESS_DB_HOST: mysql_wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
    volumes:
      - /home/jrodenas/docker/wordpress/wordpress:/var/www/html

networks:
  nextcloud:
    external: true
  internal:
    external: false
