version: "3"

volumes:
  mysql:
    driver: local
  wordpress:
    driver: local

services:
  wpdb:
    restart: unless-stopped
    image: mariadb:focal
    container_name: wpdb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    env_file:
      - wp.env
    security_opt:
      - no-new-privileges
    networks:
      - internal
    volumes:
      - ./mysql:/var/lib/mysql

  wpnginx:
    container_name: wpnginx
    image: nginx:stable-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./wordpress:/var/www/html
      - ./logs:/var/log/nginx/
      - ./conf/nginx-wp:/etc/nginx/
    links:
      - wp
    labels:
      # wordpress
      - traefik.enable=true
      - traefik.http.services.wordpress.loadbalancer.server.port=80
      - traefik.http.routers.wordpress.entrypoints=web
      - traefik.http.routers.wordpress.rule=Host(`${HOST_DOMAIN}`)
      - traefik.http.middlewares.securedwp.redirectscheme.scheme=websecure
      - traefik.http.routers.wordpress-secure.tls.certresolver=lets-encrypt
      - traefik.http.routers.wordpress.middlewares=securedwp
      - traefik.http.routers.wordpress-secure.entrypoints=websecure
      - traefik.http.routers.wordpress-secure.rule=Host(`${HOST_DOMAIN}`)
      - traefik.http.routers.wordpress-secure.tls=true
    networks:
      - nextcloud
      - internal

  wpredis:
    container_name: wpredis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - /path/to/data/wordpress/redis:/data
    networks:
      - internal

  wp:
    image: wordpress:fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - wp.env
    security_opt:
      - no-new-privileges
    networks:
      - internal
    depends_on:
      - wpdb
    volumes:
       - ./wordpress:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/php.ini

networks:
  nextcloud:
    external: true
  internal:
    external: false
